services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-ant-url
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3307:3306'
    networks: 
      - ant-url-network
networks:
  ant-url-network:
    driver: bridge